### ISSUE TITLE
Implement a whiptail bash installer

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#103]
It would be nice to implement a whiptail based bash installer that will build the all.yml, inventory and set up other options as necessary (I.E. Transmission VPN) before running the playbook. It would make the whole package a lot easier for linux noobs to run. They get twitchy when they have to work out how to use nano (or worse, vi!) and edit files themselves. I feel that this would help take the software one step closer to a FreeNAS replacement and make a great V1 milestone! 

On this note; If after initial install the git package is updated with more built in containers does everything require a full reinstall or can the new inventory be edited and the playbook run again? If the new inventory can be edited and playbook run again without a fresh install of ubuntu it would be worth implementing a cache into the whiptail script - I.E. if "inventory" already exists, load the values from it or use a separate cache file to remember the choices and load them into the whiptail script if grabbing specific lines without a major recode of the inventory file is hard.

**Comment by davestephens** [comment]
Firstly, thank you for your thoughts and for tapping them out into an issue :+1: 

I have to be honest though, I'm not keen on the idea of abstracting away Ansible and basic system administration behind a shell script, or worse, one with a GUI :smile:  

FreeNAS has a certain barrier to entry (many of us have been there!), and if users are able to navigate that and its dreadful fragmented documentation, and furthermore, install plugins on top of it (which themselves are now just Docker containers) - then I'd argue that Ansible-NAS shouldn't be a problem for them. 

Ansible-NAS is pretty well documented (increasingly so thanks to the awesome community), and has a growing user base and readily available support via multiple methods - but there is an expectation that you shouldn't mind getting your hands dirty in a few text files, and be prepared to debug issues yourself should something go wrong. 

By hiding all the basic sysadmin stuff and configuration away I'd essentially be saying "this is ready for anyone to use, even if you know nothing about system administration or are unwilling to try and debug things" - which most certainly is not the case. 

I could be totally wrong here, but I'm of the opinion that Ansible-NAS is a tinkerer's project - for tech-heads like myself that prefer to set things up and configure them on their own rather than be fed a "one size fits all" solution like FreeNAS that is a pain in the ass to manage. 

In answer to your other question:
> On this note; If after initial install the git package is updated with more built in containers does everything require a full reinstall or can the new inventory be edited and the playbook run again?

Firstly do a `git pull` and update your local copy of the repo. If you've done everything correctly your `all.yml` and `inventory` will still be intact, so then you just need to merge changes from `all.yml.dist` into your own `all.yml` and re-run. Existing containers will stay as-is, new stuff will be configured if required.

**Comment by animeai** [comment]
Fair point :) So far, I've only tested in a VM and not encountered any bugs in setup, but always found manually configuring a config file to take more time than I wanted! Thanks for the answer on updating too, I was concerned that setup might have been a one time thing and would mean a full reinstall or setting new features up manually. 

If I have time in the next month or two I might hash up a basic whiptail installer but would be more likely to work on adding new containers and fixing the port management issues (bring them all to a single place for easy editing). While I appreciate that new containers can be easily added using portainer, I like plenty of options! Are you averse to new containers being added without a specific request for them? I'd quite like to add things like teamspeak and most of the "linuxserver" dockers. I guess a separate pull request for each one I add so they can be vetoed if you don't mind more being added?

**Comment by davestephens** [comment]
Feel free to reopen if you do some work on this :+1:
