### ISSUE TITLE
Use wildcard Let's Encrypt certificate for Traefik

### ISSUE THREAD

**Issue by koenvervloesem** [davestephens/ansible-nas#135]
**Is your feature request related to a problem? Please describe.**

I'm running a couple of Docker containers on my Ansible-NAS machine that are not installed by Ansible-NAS. I'd like to use them with nice subdomains, but Traefik creates a SAN for its Let's Encrypt certificate with the Ansible-NAS services hardcoded, so I can't use them like I use the other services.

**Describe the solution you'd like**

The Traefik configuration should specify `*.{{ ansible_nas_domain }}` as the SAN for its Let's Encrypt certificate or it should be an option to use this SAN instead of the current one, which hardcodes all Ansible-NAS services.

**Describe alternatives you've considered**

For me personally, [using a self-signed wildcard certificate for Traefik](https://github.com/davestephens/ansible-nas/issues/128) is an alternative that I'm currently using (I don't expose the services to the internet).

**Additional context**

Eventually I want to migrate my setup in https://github.com/davestephens/ansible-nas/issues/128 to an internal CA with ACME server (which I'll probably want to add to Ansible-NAS with a pull request). The advantage of the latter approach is that I can keep using Traefik's acme configuration but only have to change the endpoint. That is, if this issue is solved, because I don't like to manage two systems to be able to access my services that are installed by Ansible-NAS and the ones that aren't.

**Comment by davestephens** [comment]
The reason Ansible-NAS doesn't specify a wildcard hostname as the cert SAN is because you have to do domain ownership verification with DNS, rather than through HTTP as we do now. 

To do domain verification with Traefik and DNS is a case of editing the Traefik config file to the specifics of your DNS provider, which is quite a bit more painful than the "add a wildcard dns entry" and "map ports from your router to ansible-nas" that we have in the docs now. 

The whole thinking behind Ansible-NAS is that people shouldn't be having to hack up config files themselves, everything should be through `all.yml`.

I have considered this a few times, but haven't come up with a good way to make it so that;
- it's easy to set up SSL
- it doesn't cause merge conflicts for every person that uses Traefik and subsequently wants to update from master

A workaround would be to allow specifying a list of custom hostnames, which could be merged into traefik.toml when it's templated. 

What do you think?

**Comment by koenvervloesem** [comment]
With the challenges you describe, allowing custom hostnames could be a sensible workaround, yes.

**Comment by PurpleNinja225** [comment]
I believe that commit 6b30e9afe217251c97471128c786c974cfc3ec0a fixes this issue
