### ISSUE TITLE
Plex unable to get posters/show description

### ISSUE THREAD

**Issue by dongennl** [davestephens/ansible-nas#163]
**Describe the bug**
clean install on 18.04 using the script; also installed Sonarr, Transmission, Couchpotato; everything works except Plex cannot seem to find any metadata, posters are black, no show description, actor etc. 

It appears the Plex container can't access the Internet. (using default 'host' networking).
I have a FreeNas Server running Plex as a plugin on same LAN and that is working fine, so can't be network or firewall.
I've also tried running in 'bridge' mode, but same issue.
Sonarr is running in the same docker and is working fine, getting artwork etc.

Anyone else seen this, could it be a host config issue? I'm at a loss how to fix this and this stops me from migrating from FreeNAS.

Thanks for any pointers.

**Environment**
- Ansible-NAS revision (`f96bf92`):
- Ansible version:
ansible 2.5.1
  config file = /home/dongennl/ansible-nas/ansible.cfg
  configured module search path = [u'/home/dongennl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
- Ansible-NAS operating system:
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  local
- media is on ZFS but that seems to work fine.

**Expected behavior**
Plex should be able to find metadata and show posters/descriptions.

**Actual behavior**
Black posters and 'get metadata' seems to time out; nothing in container log. 

**Steps to reproduce**
Add some shows from disk and force metadata refresh

**Comment by davestephens** [comment]
Interesting one, and not something that's caused by Ansible-NAS - we simply spin up the `linuxserver/plex` image. What version of that are you using, and what version of Plex itself?

Other things you could try (again, not related to Ansible-NAS):
- I'm assuming from your issue that you're only trying to retrieve movie metadata - does it work for music?
- What metadata source are you using? 
- Are your files named correctly for Plex to be able to search for the right thing?

I can only suggest you jump on the Plex forums and try some of the suggestions on there, you are most certainly not the first person to have this issue .eg - https://forums.plex.tv/t/unraid-linuxserver-plex-cover-art-not-downloading/440246/10

**Comment by dongennl** [comment]
Hi, you are right, not due to the script; I managed to log into the running Plex container and verify that it _could_ reach the outside world.
Turns out the posters/descriptions work ok for Films, just not TV shows. Read elsewhere that theTVDatabase are having API changes/troubles, so that is probably causing it.

Sorry!

**Comment by davestephens** [comment]
Great, glad you got it sorted :+1:
