### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by solvaholic** [davestephens/ansible-nas#246]
Thank you @davestephens and everyone who's contributed!

I'm just getting started with ansible-nas and can already tell I'm going to learn *so much* about getting things done with Ansible and Docker.

Your journey through FreeNAS toward building an alternative rings so familiar for me. I don't love zfs enough to really, fully commit to FreeNAS and I don't mind admitting I've been too lazy to really commit to FreeBSD. So your Ubuntu- and Docker-based approach (products with which I'm already familiar) with Ansible as the glue thoroughly appeals to me.

Again, thank you.

**Comment by davestephens** [comment]
Very kind of you to drop a message @solvaholic, thank you 👍

I'm pleased you're enjoying the project, it started out of FreeNAS driving me nuts and believing I could create something better myself...I think we're getting there. 

I've had little time to work on it recently (two kids at home instead of school means very little hacking time!) but hopefully normal service will resume in the not-too-distant future!

In the meantime....🍺
