### ISSUE TITLE
Enable dynamic loading of custom Ansible roles

### ISSUE THREAD

**Issue by davestephens** [davestephens/ansible-nas#594]
Enable dynamic loading of a custom list of ansible roles from `nas.yml`

**Comment by bcurran3** [comment]
I'm completely onboard with this and hope you/we can figure it out. 

About two years ago I had issues with the management of this repo. I had planned to port the concept of Ansible-NAS to PowerShell as I'm (arguably) more adept in PowerShell. PS-NAS hasn't come about as I just don't have the time. One of the core features of PS-NAS was to have a directory of active apps and a directory of inactive apps. To enable an app you'd simply drag and drop it from the repo supplied app library into the (active) apps folder and then the main script would find it in there and kick off the installation of that app via it's custom PowerShell script and configuration (XML) file. Apps in the library folder would part of the repo, apps in the apps folder would not be tracked.

So I propose that once it's figured out how to dynamically load roles from `nas.yml`, that `nas.yml` loads all roles found in `./roles`. The project can then move all **app** roles to a `./roles_library` or `./roles_unused` folder. Instead of users doing a lot of "nanoing" to enable apps, they would simply drag and drop them/copy them from `./roles_library` to `./roles` to enable them. `./roles` would be added to `.gitignore` to be not tracked other than maybe a placeholder or instruction file. Benefits include arguably faster initial setup and solving the root problem of adding additional apps without getting out of sync with the master branch.

**Comment by davestephens** [comment]
If you're using `nano` then I can understand why editing Ansible-NAS config and merging might be tedious. Use an IDE like VSCode or any of the Jetbrains stack (as mentioned in the docs) on your Ansible controller and your life will be much easier.

> ... where the user could then decide to copy it (and possibly modify it to suite their needs) over to ./roles or not.

This is exactly the same as merging code, except harder because you don't have an industry standard tool (git) helping you do it. I would recommend learning the mechanics of git merging, git pull and git stash, which will help you out in this situation.

I'm fine with the mechanics of Ansible standards. I don't have a desire to change that and confuse people that are also used to it. I'm happy to try and support dynamic loading for customisation reasons, but not move away from the Ansible way of doing things, because it works just fine.

**Comment by davestephens** [comment]
Dynamic loading of modules doesn't seem to be a thing. And not something that anyone seems to want, so closing this issue.
