### ISSUE TITLE
trouble with zfs/samba

### ISSUE THREAD

**Issue by chrisbutler** [davestephens/ansible-nas#6]
hey @davestephens, thanks for putting this together! i can't seem to get samba shares working... it's not connectable, and i've tried messing around with some obvious settings/permissions and i'm getting nowhere

i also can't get the playbook to run on ubuntu server without commenting out this line: https://github.com/davestephens/ansible-nas/blob/master/tasks/general.yml#L20

this is my first time using ansible... am i missing something obvious?

**Comment by davestephens** [comment]
Hey @chrisbutler, thanks for getting in touch.

What version of Ubuntu server are you using? I'm going to take a punt and say it's something newer than 16.04 - a quick search has revealed the zfs package was actually a virtual package (ie a pointer to >=1 other packages) which they've removed in newer Ubuntu versions.  To get things working you should be able to replace it with `zfs-linux` or just remove it entirely (as you have done) if you don't care about zfs. I'll get that fixed up in the code. 

As for Samba, couple of things:

- Can you check it's definitely installed ok and running? `samba --version` and 
- On the assumption that you're using something other than 16.04 - can you let me know what Ubuntu you're using and I'll spin up a VM and test the playbook out? 
- Minor point, but I assume the paths in your shares point to real paths on the filesystem that aren't locked down to readonly?
- Rather than browsing to `\\computername` does browsing directly to `\\computername\sharename` work?

Thanks for trying ansible-nas out, hopefully we can work out what's going wrong!

**Comment by davestephens** [comment]
Created #7 to track Ubuntu 18.04 compatibility.

**Comment by chrisbutler** [comment]
- yep, i'm using 18.04. it wants `zfsutils-linux` now, it seems
- looks like samba wasn't installed... i installed it with apt but my user credentials don't work to log in
- yes, the shares in the config are actual paths
- including the `\sharename` doesn't seem to make a difference

thoughts on the samba situation?

**Comment by davestephens** [comment]
OK, so this now works fine. 

Part of it was Ubuntu 18.04 package names changing, and part of it was me making a massive cut and paste fail (basically the samba and docker roles weren't being run :man_facepalming:)

If you'd be so kind as to pull the latest from master and run again it's be appreciated!

**Comment by chrisbutler** [comment]
ok, so i ran it again and got everything mostly working! thank you!

but... which user should i be trying to log in as for samba? i can't log in as my primary ubuntu user, or as a guest 😢

**Comment by chrisbutler** [comment]
so i tried again with a fresh box, and i'm able to access the shares from the user specified in the config now!

it has to be the specific share directories (e.g. `/tv`), trying to connect to the root and list each directory doesn't currently work, which is likely just a configuration thing?

i'm guessing that my original issue accessing shares directly was related to fs permissions on the box, and now that the samba role step runs i can definitely close this issue
